application:
  subdomain: codeg
  public_path:
    - /
  upstreams:
    - location: /
      backend: http://codeg:3080/

  injects:
    - id: codeg-token-autofill
      when:
        - /login
      do:
        - src: builtin://simple-inject-password
          params:
            password: '{{ index .U "codeg_token" }}'
            allowPasswordOnly: true

services:
  codeg:
    # ghcr.io/xintaofei/codeg:0.8.8
    image: registry.lazycat.cloud/czyt/xintaofei/codeg:c858516e649fc07f
    user: root
    environment:
      - CODEG_TOKEN={{.U.codeg_token}}
    binds:
      - /lzcapp/var/data:/data
      - /lzcapp/var/claude:/root/.claude
      - /lzcapp/var/gemini:/root/.gemini
      - /lzcapp/var/codex:/root/.codex
      - /lzcapp/var/projects:/projects
    healthcheck:
      test:
        - CMD-SHELL
        - curl -f http://localhost:3080/ || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
